config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sessions/new'
  get 'sessions/create'

  get('/', {to: 'ideas#index', as: :root})

  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only: [ :create, :destroy ]
    resources :joins, shallow: true, only: [ :create, :destroy ]
    get :liked, on: :collection
    get :joined, on: :collection

  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

end

app/models/idea.rb
class Idea < ApplicationRecord

    has_many :reviews, dependent: :destroy
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
    has_many :joins, dependent: :destroy
    has_many :joiners, through: :joins, source: :user

    validates(:title, presence: true, uniqueness: true)

    validates :description, presence: { message: "must exist"}

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_idea, only: [:show, :edit, :update, :destroy]
    before_action :authorize!, only: [:edit, :update, :destroy]

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      flash[:notice] = "Idea created successfully"
      redirect_to idea_path(@idea)
    else
      # render views/ideas/new.html.erb
      render :new
    end
  end

  def show
    @review = Review.new
    @reviews = @idea.reviews.order(created_at: :desc)
    # @like = @idea.likes.find_by(user: current_user)
  end

  def index
    # @ideas = Idea.all

    @ideas = Idea.order(created_at: :desc)
    # @like = @idea.likes.find_by(user: current_user)

  end

  def edit
    unless can?(:crud, @idea)
      redirect_to root_path, alert: 'Not Authorized'
    end
  end

  def update
    # attempt to edit the existing question with new values
    if @idea.update idea_params
      redirect_to idea_path(@idea)
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = "Idea Deleted!"
    @idea.destroy
    redirect_to ideas_path
  end

  def liked
    @ideas = current_user.liked_ideas.order('likes.created_at DESC')
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def find_idea
    # get the current value inside of the db
    @idea = Idea.find params[:id]
  end

  def authorize!
    redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @idea)
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%# https://guides.rubyonrails.org/form_helpers.html %>
<%= form_for @idea do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/ideas/_list.html.erb
<% @ideas.each do |idea| %>
  <div>
    <h2><%= link_to idea.title, idea_path(idea) %></h2>
    <p><%= idea.description %></p>
    <h4>Created by: <%= idea.user.full_name  || 'DELETED'%></h4>

  <% if user_signed_in? && can?(:like, idea) %>

    <% like = current_user.likes.find_by_idea_id(idea) %>

    <% if like %>
        <%= link_to "Unlike", like_path(like), method: :delete %>
    <% else %>
        <%= link_to "Like", idea_likes_path(idea), method: :post %>
    <% end %>
    <small>
    <%= pluralize(idea.likes.count, "like") %>
    </small>
  <% end %>
  
  <% if user_signed_in? && can?(:join, idea) %>
  
    <% join = current_user.joins.find_by_idea_id(idea) %>

    <% if join %>
        <%= link_to "Joined", join_path(join), method: :delete %>
    <% else %>
        <%= link_to "Join", idea_joins_path(idea), method: :post %>
    <% end %>
    <small>
    <%= pluralize(idea.joins.count, "member") %>
    </small>
  <% end %>


    <hr>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<div class="container">

<h1>Edit Ideas</h1>

<%= render "form" %>

</div>

app/views/ideas/index.html.erb
</br>
<div class="container">
<%= render 'list' %>

</div>

app/views/ideas/new.html.erb
<div class="container">

<h1>New Ideas</h1>

<%= render "form" %>

</div>

app/views/ideas/show.html.erb
<div class="container">
  <h1><%= @idea.title %></h1>
  <p><%= @idea.description %></p>
  <p><%= @idea.created_at %></p>
  <h4>Created by: <%= @idea.user.full_name  || 'DELETED'%></h4>


  <div>
    <%= link_to "Edit", edit_idea_path(@idea)%>
    <%= link_to "Delete", idea_path(@idea), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>



  <%= form_with(model: [@idea, @review], local: true) do |f| %>
  <% if @review.errors.any? %>
    <ul>
      <% @review.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.text_area(
    :body,
    cols: 50,
    rows: 5,
    placeholder: "What are your thoughts?",
    class: "form-control"
    ) %>
  </div>
  <%= f.submit "Review" %>
  <% end %>

  <hr />

  <ul class="review-list">
    <% @reviews.each do |review| %>
      <li>
        <p>
          <%= review.body %> <br />
            <small>
              <%= link_to(
                "Delete",
                idea_review_path(@idea, review),
                method: :delete,
                data: {
                  confirm: "Are you sure?"
                }
              ) %>
            </small>

          <% if user_signed_in? && can?(:like, review) %>
              <% like = current_user.likes.find_by_review_id(review) %>
              <% if like %>
                  <%= link_to "Unlike", like_path(like), method: :delete %>
              <% else %>
                  <%= link_to "Like", review_likes_path(review), method: :post %>
              <% end %>
              <small>
              <%= pluralize(review.likes.count, "like") %>
              </small>
          <% end %>
          |
          <small>
            Reviewed <%= time_ago_in_words(review.created_at) %> ago
          </small>
        </p>
      </li>
    <% end %>
  </ul>
</div>