config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sessions/new'
  get 'sessions/create'

  get('/', {to: 'ideas#index', as: :root})

  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only: [ :create, :destroy ]
    resources :joins, shallow: true, only: [ :create, :destroy ]
    get :liked, on: :collection
    get :joined, on: :collection

  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Idea Factory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  </head>


  <body>
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
    <% end %>

    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">
        <img src="https://foroalfa.org/imagenes/ilustraciones/idea.png" height="80" class="d-inline-block" alt="">
        Idea Factory
      </a>

      <ul class="mr-auto">
    </ul>

     <ul class="justify-content-end">    
      <li class="nav-item nav-link">
      
      <% if user_signed_in?%>
        Hello <%= current_user.full_name %>,
        <%= link_to "Logout", session_path, method: :delete,
        data: {confirm: "Are you sure you want to log out?"}%>
      <%else%>
      </li>
        <%= link_to "Login", new_session_path %> |
        <%= link_to "Sign Up", new_user_path %>
      <% end %>
      |
      <%= link_to 'New Idea', new_idea_path %>
      |
      <%= link_to 'All Ideas', ideas_path %>
 
    </ul>

    </nav>
    <%= yield %>
  </body>

</html>